# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PBIF # the title of your site should go here
description: |  # this means to ignore newlines (until baseurl:)
  The Pacific Biodiversity Information Facility portal to present all of the Pacific occurrences of biodiversity data currently available on GBIF. 
  So only using a geographical scope to filter the GBIF dataset as a whole.
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pbif.sprep.org" # the base hostname & protocol for your site, e.g. http://example.com

#SOCIAL PROFILES
email: bradleym@sprep.org
#twitter_username: jekyllrb
#github_username:  jekyll
#youtube_username: PRISMSS


# Build settings

theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme


remote_theme: gbif/jekyll-hp-base-theme

# for usage in the standard privacy layout
privacy:
  name: Pacific Biodiversity Information Facility (PBIF)
  domain: pbif.sprep.org
  contactEmail: davidm@sprep.org
  helpdeskEmail: waynea@sprep.org

# The text for the terms can be changed by adding translations for 'terms', 'acceptTerms' and 'rejectTerms' in `/_data/translations.yml`.
siteMeasurements:
  enable: true # When enabled there will be a popup asking the user for their consent. If they accept then the function "attachMeasurements" will be called. You can overwrite this function by adding a file `/_includes/js/measure.js` and replace the function.
  GA_ID: "G-0R59CM3226" # Your Google analytics ID. Sometimes they start with UA-XXXXX-X other times with G-XXXXXXXX depending on how you set it up
  termsVersion: "2021-07-06" # A version number for your terms. If you change this, then the users will see the popup again asking them to confirm/reject anew.

algae:
  rootLang: en
  latestPostLimit: 2
  logo: /assets/images/SPREP-PROE-wide-acronyms-white.png  # Logo in navbar, will be displayed with 28px height
  logoAndTitle: true           # include the title next to the logo
  archive_permalink: /news/    # Permalink of page using archive.html layout, required when using post categories
  style:
    square: true
    # square: false               # Should corners be square or rounded
    colors:
      primary: "#176fe3"          # Primary color of your brand. Use HEX code. Used for buttons and links
      links: "#176fe3"          # What color should links have. Use a HEX code. DEfault is primary color. 
    coloredHeadlineLinks: true   # If a headline is a link, then use the link color. Default is true. 
  navbar:                         # RELATED TO NAVIGATION BAR
    # brandBackground: /assets/images/2.png     # Define a custom background for the logo/title in the top navigation bar
    #color: green
    #color: "#acd5fa"             # What color should the navbar be?
    hasWhiteText: true          # Should the text color be white?

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - .LICENSE
  - .netlify.toml
  - .README.md

defaults:
  - # English
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      lang: en
      
  - # Samoan
    scope:
      path: "sm/"
    values:
      lang: sm
  - # French
    scope:
      path: "fre/"
    values:
      lang: fre
  - # Fijian
    scope:
      path: "fij/"
    values:
      lang: fij
  - # Tongan
    scope:
      path: "to/"
    values:
      lang: to
  - # Tokelauan
    scope:
      path: "tk/"
    values:
      lang: tk
  - # Tuvaluan
    scope:
      path: "tv/"
    values:
      lang: tv
  - # Solomons Pidgen
    scope:
      path: "sb/"
    values:
      lang: sb
  - # Niue
    scope:
      path: "nu/"
    values:
      lang: nu    
  - # RMI
    scope:
      path: "rmi/"
    values:
      lang: rmi
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      lang: [en,fij,fre,sm,nu,to,tk,tv,sb,rmi]
      permalink: "/post/:year/:slug/"   # Use /post/yyyy/{filename}/ as permalink for all posts
